import { randomBytes } from 'node:crypto'
import { spawn as nodeSpawn } from 'node:child_process'
import { mkdir, writeFile, appendFile, rm } from 'node:fs/promises'

/** Only this compose/docker network is allowed for lab deploys. */
export const ALLOWED_NETWORK = 'targets'

export type EnvMap = Record<string, string | undefined>

export type ExecResult = {
  stdout: string
  stderr: string
  exitCode: number
}

export type SpawnFn = (
  command: string,
  args: string[],
  opts?: { signal?: AbortSignal; env?: EnvMap; cwd?: string },
) => Promise<ExecResult>

export type FsLike = {
  mkdir(path: string, opts?: { recursive?: boolean }): Promise<void>
  writeFile(path: string, data: string | Uint8Array): Promise<void>
  appendFile(path: string, data: string): Promise<void>
  rm(path: string, opts?: { recursive?: boolean; force?: boolean }): Promise<void>
}

export type ClientOptions = {
  spawn?: SpawnFn
  fs?: FsLike
  env?: EnvMap
  signal?: AbortSignal
  now?: () => Date
  randomId?: () => string
}

export type DeploySource = 'git' | 'image' | 'compose'

export type DeployUpArgs = {
  source: DeploySource
  ref: string
  /** Compose/docker network. Must be `targets` (default). */
  network?: string
  id?: string
}

export type DeployUpResult = {
  id: string
  project: string
  network: string
  baseUrl: string
  logPath: string
}

export type DeployDownArgs = {
  id: string
}

export type DeployDownResult = {
  id: string
  project: string
  ok: true
}

export class DeployNetworkError extends Error {
  readonly network: string
  constructor(network: string) {
    super(`deploy refuses network '${network}'; only '${ALLOWED_NETWORK}' is allowed`)
    this.name = 'DeployNetworkError'
    this.network = network
  }
}

export function redactSecrets(value: unknown): unknown {
  const secretKey = /token|secret|authorization|api[_-]?key|private|password|passwd|credential/i
  const walk = (input: unknown): unknown => {
    if (Array.isArray(input)) return input.map(walk)
    if (input && typeof input === 'object') {
      const out: Record<string, unknown> = {}
      for (const [k, v] of Object.entries(input as Record<string, unknown>)) {
        out[k] = secretKey.test(k) ? '[redacted]' : walk(v)
      }
      return out
    }
    return input
  }
  return walk(value)
}

export function renderSafe(_args: unknown, value: unknown): Array<{ type: 'text'; text: string }> {
  return [{ type: 'text', text: JSON.stringify(redactSecrets(value)) }]
}

export function composeProjectName(id: string): string {
  const clean = id.trim()
  if (!clean) throw new Error('deploy id is required')
  return `neo-target-${clean}`
}

/** Hard-fail unless the requested compose network is exactly `targets`. */
export function assertAllowedNetwork(network: string | undefined | null): string {
  const n = String(network ?? ALLOWED_NETWORK).trim()
  if (n !== ALLOWED_NETWORK) {
    throw new DeployNetworkError(n || '(empty)')
  }
  return n
}

/** Docker engine name for the external targets network (compose sets name: neo_targets). */
export function targetsNetworkName(env: EnvMap = process.env): string {
  const value = env.NEO_TARGETS_NETWORK?.trim()
  return value || 'neo_targets'
}

export function newDeployId(): string {
  return randomBytes(4).toString('hex')
}

function throwIfAborted(signal?: AbortSignal): void {
  if (signal?.aborted) {
    const err = new Error('aborted')
    err.name = 'AbortError'
    throw err
  }
}

export function defaultSpawn(
  command: string,
  args: string[],
  opts?: { signal?: AbortSignal; env?: EnvMap; cwd?: string },
): Promise<ExecResult> {
  return new Promise((resolve, reject) => {
    const child = nodeSpawn(command, args, {
      signal: opts?.signal,
      env: opts?.env as Record<string, string> | undefined,
      cwd: opts?.cwd,
    })
    const stdout: Buffer[] = []
    const stderr: Buffer[] = []
    child.stdout.on('data', (chunk) => stdout.push(chunk))
    child.stderr.on('data', (chunk) => stderr.push(chunk))
    child.on('error', reject)
    child.on('close', (code) => {
      resolve({
        stdout: Buffer.concat(stdout).toString('utf8'),
        stderr: Buffer.concat(stderr).toString('utf8'),
        exitCode: typeof code === 'number' ? code : 1,
      })
    })
  })
}

const defaultFs: FsLike = { mkdir, writeFile, appendFile, rm }

function resolveSource(source: string): DeploySource {
  if (source === 'git' || source === 'image' || source === 'compose') return source
  throw new Error(`deploy source must be git|image|compose (got '${source}')`)
}

function workspaceRoot(env: EnvMap): string {
  return (env.NEO_WORKSPACE ?? '/workspace').replace(/\/+$/, '') || '/workspace'
}

function overrideCompose(networkDockerName: string): string {
  return [
    '# Generated by neo-tools-deploy — forces isolated targets network only.',
    'networks:',
    '  default:',
    '    name: ' + networkDockerName,
    '    external: true',
    '  targets:',
    '    name: ' + networkDockerName,
    '    external: true',
    '',
  ].join('\n')
}

async function runLogged(
  spawn: SpawnFn,
  fs: FsLike,
  logPath: string,
  command: string,
  args: string[],
  opts: { signal?: AbortSignal; env?: EnvMap; cwd?: string },
): Promise<ExecResult> {
  throwIfAborted(opts.signal)
  await fs.appendFile(logPath, `\n$ ${command} ${args.join(' ')}\n`)
  const result = await spawn(command, args, opts)
  await fs.appendFile(
    logPath,
    `${result.stdout}${result.stderr}exit=${result.exitCode}\n`,
  )
  return result
}

export async function deployUp(args: DeployUpArgs, opts: ClientOptions = {}): Promise<DeployUpResult> {
  throwIfAborted(opts.signal)
  const env = opts.env ?? process.env
  const network = assertAllowedNetwork(args.network)
  const source = resolveSource(args.source)
  const ref = String(args.ref ?? '').trim()
  if (!ref) throw new Error('deploy ref is required')

  const id = (args.id?.trim() || (opts.randomId ?? newDeployId)())
  const project = composeProjectName(id)
  const dockerNet = targetsNetworkName(env)
  const root = workspaceRoot(env)
  const dir = `${root}/deploy/${id}`
  const logPath = `${dir}/compose.log`
  const fs = opts.fs ?? defaultFs
  const spawn = opts.spawn ?? defaultSpawn

  await fs.mkdir(dir, { recursive: true })
  await fs.writeFile(logPath, `deploy_up source=${source} ref=${ref} network=${network} project=${project}\n`)

  if (source === 'image') {
    const name = `${project}-app`
    const result = await runLogged(spawn, fs, logPath, 'docker', [
      'run', '-d',
      '--name', name,
      '--network', dockerNet,
      '--network-alias', id,
      '--label', `neo.deploy.id=${id}`,
      '--label', `neo.deploy.project=${project}`,
      ref,
    ], { signal: opts.signal, env })
    if (result.exitCode !== 0) {
      throw new Error(`docker run failed (exit ${result.exitCode}): ${result.stderr || result.stdout}`)
    }
  } else if (source === 'git') {
    const srcDir = `${dir}/src`
    await fs.mkdir(srcDir, { recursive: true })
    const clone = await runLogged(spawn, fs, logPath, 'git', [
      'clone', '--depth', '1', ref, srcDir,
    ], { signal: opts.signal, env })
    if (clone.exitCode !== 0) {
      throw new Error(`git clone failed (exit ${clone.exitCode}): ${clone.stderr || clone.stdout}`)
    }
    const overridePath = `${dir}/network.override.yml`
    await fs.writeFile(overridePath, overrideCompose(dockerNet))
    const up = await runLogged(spawn, fs, logPath, 'docker', [
      'compose',
      '-p', project,
      '-f', 'docker-compose.yml',
      '-f', overridePath,
      'up', '-d', '--remove-orphans',
    ], { signal: opts.signal, env, cwd: srcDir })
    if (up.exitCode !== 0) {
      // Try compose.yaml fallback
      const up2 = await runLogged(spawn, fs, logPath, 'docker', [
        'compose',
        '-p', project,
        '-f', 'compose.yaml',
        '-f', overridePath,
        'up', '-d', '--remove-orphans',
      ], { signal: opts.signal, env, cwd: srcDir })
      if (up2.exitCode !== 0) {
        throw new Error(`docker compose up failed (exit ${up2.exitCode}): ${up2.stderr || up2.stdout}`)
      }
    }
  } else {
    // compose: ref is a compose file path
    const overridePath = `${dir}/network.override.yml`
    await fs.writeFile(overridePath, overrideCompose(dockerNet))
    const up = await runLogged(spawn, fs, logPath, 'docker', [
      'compose',
      '-p', project,
      '-f', ref,
      '-f', overridePath,
      'up', '-d', '--remove-orphans',
    ], { signal: opts.signal, env })
    if (up.exitCode !== 0) {
      throw new Error(`docker compose up failed (exit ${up.exitCode}): ${up.stderr || up.stdout}`)
    }
  }

  const baseUrl = `http://${id}:80`
  await fs.writeFile(`${dir}/meta.json`, JSON.stringify({
    id, project, network, source, ref, baseUrl, logPath, dockerNetwork: dockerNet,
  }, null, 2))

  return { id, project, network, baseUrl, logPath }
}

export async function deployDown(args: DeployDownArgs, opts: ClientOptions = {}): Promise<DeployDownResult> {
  throwIfAborted(opts.signal)
  const env = opts.env ?? process.env
  const id = String(args.id ?? '').trim()
  if (!id) throw new Error('deploy id is required')
  const project = composeProjectName(id)
  const root = workspaceRoot(env)
  const dir = `${root}/deploy/${id}`
  const logPath = `${dir}/compose.log`
  const fs = opts.fs ?? defaultFs
  const spawn = opts.spawn ?? defaultSpawn

  await fs.mkdir(dir, { recursive: true })
  const down = await runLogged(spawn, fs, logPath, 'docker', [
    'compose', '-p', project, 'down', '--remove-orphans', '-v',
  ], { signal: opts.signal, env })
  // Also remove image-mode container if present
  await runLogged(spawn, fs, logPath, 'docker', [
    'rm', '-f', `${project}-app`,
  ], { signal: opts.signal, env })

  if (down.exitCode !== 0) {
    // compose down may fail if project was image-only; still OK if rm succeeded
    await fs.appendFile(logPath, `compose down exit=${down.exitCode} (ignored if image-only)\n`)
  }

  return { id, project, ok: true }
}
